package test:llm;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface test-llm-api {
  test1: func() -> string;
  test2: func() -> string;
  test3: func() -> string;
  test4: func() -> string;
  test5: func() -> string;
  test6: func() -> string;
  test7: func() -> string;
}

world test-llm {
  import golem:llm/llm@1.0.0;
  export test-llm-api;
}
