// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
//   * with "golem:llm/llm@1.0.0" = "golem_llm::golem::llm::llm"
//   * generate_unused_types
use golem_llm::golem::llm::llm as __with_name0;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:golem:llm-openai@1.0.0:llm-library:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1725] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbb\x0c\x01A\x02\x01\
A\x02\x01BM\x01m\x04\x04user\x09assistant\x06system\x04tool\x04\0\x04role\x03\0\0\
\x01m\x06\x0finvalid-request\x15authentication-failed\x13rate-limit-exceeded\x0e\
internal-error\x0bunsupported\x07unknown\x04\0\x0aerror-code\x03\0\x02\x01m\x06\x04\
stop\x06length\x0atool-calls\x0econtent-filter\x05error\x05other\x04\0\x0dfinish\
-reason\x03\0\x04\x01m\x03\x03low\x04high\x04auto\x04\0\x0cimage-detail\x03\0\x06\
\x01k\x07\x01r\x02\x03urls\x06detail\x08\x04\0\x09image-url\x03\0\x09\x01p}\x01k\
s\x01r\x02\x04data\x0b\x09mime-type\x0c\x04\0\x0cimage-source\x03\0\x0d\x01q\x03\
\x04text\x01s\0\x05image\x01\x0a\0\x0cinline-image\x01\x0e\0\x04\0\x0ccontent-pa\
rt\x03\0\x0f\x01p\x10\x01r\x03\x04role\x01\x04name\x0c\x07content\x11\x04\0\x07m\
essage\x03\0\x12\x01r\x03\x04names\x0bdescription\x0c\x11parameters-schemas\x04\0\
\x0ftool-definition\x03\0\x14\x01r\x03\x02ids\x04names\x0earguments-jsons\x04\0\x09\
tool-call\x03\0\x16\x01ky\x01r\x04\x02ids\x04names\x0bresult-jsons\x11execution-\
time-ms\x18\x04\0\x0ctool-success\x03\0\x19\x01r\x04\x02ids\x04names\x0derror-me\
ssages\x0aerror-code\x0c\x04\0\x0ctool-failure\x03\0\x1b\x01q\x02\x07success\x01\
\x1a\0\x05error\x01\x1c\0\x04\0\x0btool-result\x03\0\x1d\x01r\x02\x03keys\x05val\
ues\x04\0\x02kv\x03\0\x1f\x01kv\x01ps\x01k\"\x01p\x15\x01p\x20\x01r\x07\x05model\
s\x0btemperature!\x0amax-tokens\x18\x0estop-sequences#\x05tools$\x0btool-choice\x0c\
\x10provider-options%\x04\0\x06config\x03\0&\x01r\x03\x0cinput-tokens\x18\x0dout\
put-tokens\x18\x0ctotal-tokens\x18\x04\0\x05usage\x03\0(\x01k\x05\x01k)\x01r\x05\
\x0dfinish-reason*\x05usage+\x0bprovider-id\x0c\x09timestamp\x0c\x16provider-met\
adata-json\x0c\x04\0\x11response-metadata\x03\0,\x01p\x17\x01r\x04\x02ids\x07con\
tent\x11\x0atool-calls.\x08metadata-\x04\0\x11complete-response\x03\0/\x01r\x03\x04\
code\x03\x07messages\x13provider-error-json\x0c\x04\0\x05error\x03\01\x01q\x03\x07\
message\x010\0\x0ctool-request\x01.\0\x05error\x012\0\x04\0\x0achat-event\x03\03\
\x01k\x11\x01k.\x01r\x02\x07content5\x0atool-calls6\x04\0\x0cstream-delta\x03\07\
\x01q\x03\x05delta\x018\0\x06finish\x01-\0\x05error\x012\0\x04\0\x0cstream-event\
\x03\09\x04\0\x0bchat-stream\x03\x01\x01h;\x01p:\x01k=\x01@\x01\x04self<\0>\x04\0\
\x1c[method]chat-stream.get-next\x01?\x01@\x01\x04self<\0=\x04\0%[method]chat-st\
ream.blocking-get-next\x01@\x01p\x13\x01@\x02\x08messages\xc1\0\x06config'\04\x04\
\0\x04send\x01B\x01o\x02\x17\x1e\x01p\xc3\0\x01@\x03\x08messages\xc1\0\x0ctool-r\
esults\xc4\0\x06config'\04\x04\0\x08continue\x01E\x01i;\x01@\x02\x08messages\xc1\
\0\x06config'\0\xc6\0\x04\0\x06stream\x01G\x04\0\x13golem:llm/llm@1.0.0\x05\0\x04\
\0\"golem:llm-openai/llm-library@1.0.0\x04\0\x0b\x11\x01\0\x0bllm-library\x03\0\0\
\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.220.0\x10wit-bind\
gen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
